import { SnowFallErrorData } from "./errors";
import { WasmModule } from "./snowfall";

/**
 * Options for the SnowFall compiler.
 */
export interface CompileOptions {
	debugInfo: boolean;
}

/**
 * The result of a compilation, returned from the Wasm module.
 */
interface CompileResult {
	bytecode: string | null;
	errors: SnowFallErrorData[];
}

/**
 * A custom error class to represent one or more compilation errors.
 */
export class SnowFallCompilerError extends Error {
	public errors: SnowFallErrorData[];

	constructor(errors: SnowFallErrorData[]) {
		const message =
			`Compilation failed with ${errors.length} error(s).\n` +
			errors.map((e) => `  - [${e.code}] ${e.message} (at ${e.line}:${e.column})`).join("\n");
		super(message);
		this.name = "SnowFallCompilerError";
		this.errors = errors;
	}
}

/**
 * Provides an interface to the SnowFall compiler implemented in Wasm.
 */
export class SnowFallCompiler {
	private wasm: WasmModule;

	constructor(wasmModule: WasmModule) {
		this.wasm = wasmModule;
	}

	/**
	 * Compiles a SnowFall source string into bytecode.
	 * @param source The source code to compile.
	 * @param options Compilation options.
	 * @returns The generated bytecode as a string.
	 * @throws {SnowFallCompilerError} If compilation fails.
	 */
	public compile(source: string, options: CompileOptions = { debugInfo: false }): string {
		const result: CompileResult = this.wasm.compile(source, options);

		if (result.errors && result.errors.length > 0) {
			throw new SnowFallCompilerError(result.errors);
		}

		if (result.bytecode === null) {
			// This case should ideally not happen if errors are always reported,
			// but it's good practice to handle it.
			throw new Error("Compilation failed, but no errors were reported.");
		}

		return result.bytecode;
	}
}
